# Перша секція в файлі не обов'язкова та описує назву  Pipeline:
name: KBOT-CICD

# Визначимо подію, яка запустить виконання workflow процесу.
on:
  push:
    branches:
      - develop
# блок задач який налаштовано на запуск завдання на новій ВМ з останньою версією ubuntu
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract Helm values
        id: helm
        run: |
          TAG=$(yq '.image.tag' helm/values.yaml)
          OS=$(yq '.image.os' helm/values.yaml)
          ARCH=$(yq '.image.arch' helm/values.yaml)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "OS=$OS" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --platform $OS/$ARCH \
            -t ghcr.io/slavaslyder/kbot:${TAG}-${OS}-${ARCH} .

      - name: Push Docker image
        run: docker push ghcr.io/slavaslyder/kbot:${TAG}-${OS}-${ARCH}
